version: '3'
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    environment:
      - DB_URI='mongodb://localhost:27018/db-name'
      - JWT_SECRET_KEY='9zVW]9cBNMbO'
      - SENDER_MAIL='sample@gmail.com'
      - SENDER_MAIL_PW='123'
    ports:
      - '8080:8080'
    external_links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo:latest
    command: mongod --port 27018
    ports:
      - '27018:27018'